### model
model_name_or_path: /mnt/sdb3/qwen2.5_32B
adapter_name_or_path: 
trust_remote_code: true

### method
finetuning_type: lora

### dataset
task: mmlu_test  # choices: [mmlu_test, ceval_validation, cmmlu_test]
template: qwen
lang: en
n_shot: 5

### output
save_dir: saves/eval/qwen2.5-32b-sft

### eval
batch_size: 4
